### ISSUE TITLE
tags page not working on windows

### ISSUE THREAD

**Issue by absurdist** [abhn/Elementary#11]
Hello

this is the project I've been looking for, this is great work

using ruby 2.6.6p146 (2020-03-31 revision 67876) 

on window 10

does not produce the tags page correctly.

cloning straight from git, 
running 
bundle update
bundle exec jekyll serve

The tags page produces just a single item

the number:

- 6

which links back to 

http://localhost:4000/tags#

**Comment by absurdist** [comment]
ok so the issue seems to be group_by isn't doing on my machine what it's doing on your machine,

but group_by_exp is working

{% assign alltags =  alldocs | map: 'tags' | join: ','  | split: ','  | group_by_exp: "tag" , "tag"  %}


I'll do PR

**Comment by abhn** [comment]
Thanks for raising this issue.

**Comment by mathew-j-davis** [comment]
you're welcome
