### ISSUE TITLE
Add details about the Gemfile

### ISSUE THREAD

**Issue by mgifford** [abhn/Elementary#3]
You have the following in the README "Add gem 'elementary', path: 'elementary' to your Gemfile"

But if I'm just exploring this I won't know what a Gemfile is. 

I think in this case we just need

```
source 'https://rubygems.org'

gem 'elementary', path: 'elementary'
```

**Comment by abhn** [comment]
Thank you for your feedback @mgifford 

I'll elaborate it a bit
