### ISSUE TITLE
Excluding the ./elementary directory

### ISSUE THREAD

**Issue by mgifford** [abhn/Elementary#4]
You also say "Add ./elementary to exclude section of _config.yml " which if you've just created the _config.yml and there isn't already an exclude section, it would just be this, right:

```
exclude:
  - ./elementary
```

**Comment by abhn** [comment]
Nice, thank you again :) 

It is easy to miss such things when you're working on it in the flow, but it definitely makes a tonne of sense.

**Comment by mgifford** [comment]
Thanks @abhn and ya, always easier to have someone from the outside come in and highlight things that were assumed.
